baseURL = "https://josephscott.org/"
languageCode = "en-us"
title = "Joseph Scott"
disableHugoGeneratorInject = true
copyright = "© Copyright {year} Joseph Scott"

theme = "burgontan"

rssLimit = 25

[markup.goldmark.renderer]
unsafe= true

[[menu.main]]
	name = "Tags"
	url = "/tags"
[[menu.main]]
	name = "Archive"
	url = "/archive"
