baseURL = "https://josephscott.org/"
languageCode = "en-us"
title = "Joseph Scott"
disableHugoGeneratorInject = true

theme = "burgontan"

rssLimit = 25

[params]
githubcomments = "josephscott/comments-josephscott.org"

[markup.goldmark.renderer]
unsafe= true
